name: DB Backup
on:
    workflow_run:
        workflows: ["PR Validation"]
        types: 
            - completed
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight
jobs:
    backup:
        runs-on: ubuntu-latest
        environment: Prod
        env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER: ${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Docker compose
              run: docker-compose -f docker-compose.yml up -d --build
            - name: Verify dir
              run: mkdir -p ./backup
            - name: Make backup
              run: |
                docker-compose -f docker-compose.yml exec -ti db bash -c 'mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /backup/backup_$(date +%F_%H-%M-%S).sql'
            - name: Delete old backups
              run: docker-compose -f docker-compose.yml exec -ti db bash -c 'find /backup -type f -name "*.sql" -mtime +7 -exec rm {} \;'
            - name: Copy backup to host
              run: docker mv $(docker-compose -f docker-compose.yml ps -q db):/backup/* ./backup
            - name: Upload backup artifact
              uses: actions/upload-artifact@v3
              with:
                name: db-backups
                path: ./backup
            - name: Verify
              run: ls ./backup
              
            

