name: DB Backup
on:
    workflow_run:
        workflows: ["Deploy"]
        types: 
            - completed
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight
jobs:
    backup:
        environment: Prod
        env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER: ${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        runs-on: ubuntu-latest
        steps:

          - name: Install SSH Key
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSH_KEY }}
              known_hosts: 'placeholder'

          - name: Adding Known Hosts
            run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
          - name: Make backup dir
            run: |
              ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ./backup"

          - name: Make backup
            run: |
              ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker exec -ti db bash -c 'mysqldump -h db -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > ./backup/$(date +%F_%H-%M-%S).sql'"

          - name: Clean up old backups on VM
            run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "find ~/backup -type f -name '*.sql' -mtime +7 -exec rm {} \;"
              
            

