name: Deploy
on:
    workflow_run:
        workflows: ["PR Validation"]
        types: 
            - completed
        branches: master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            # - name: Build docker image test
            #   run: docker build --target prod -t myapp:prod .
            # - name: Deploy to production server
            #   run: 
