name: Deploy
on:
    workflow_run:
        workflows: ["Testing"]
        types: 
            - completed
        branches: master
    pull_request:
        types:
            - closed
jobs:
    deployment:
      if: github.event.pull_request.merged == true
      environment: Prod
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        
      runs-on: ubuntu-latest
      steps:
        # - name: Install SSH Key
        #   uses: shimataro/ssh-key-action@v2
        #   with:
        #     key: ${{ secrets.ID_RSA }}
        #     known_hosts: 'placeholder'

        # - name: Adding Known Host
        #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

        - name: Checkout code
          uses: actions/checkout@v4
          
        # - name: Copy files with SCP
        #   run: |
        #     scp -rv /home/runner/work/assignment1/assignment1 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home
        #     ls /home/runner/work/assignment1/assignment1/
        # - name: Spin up containers
        #   run: |
        #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd assignment1; docker compose down; docker compose up --build -d"
        - name: Change commit version
          run: |
            chmod u+x version.sh
            ./version.sh
        - name: Git config
          run: |
            git config --global user.name "${{ secrets.GIT_USERNAME }}"
            git config --global user.email "${{ secrets.GIT_EMAIL }}"
        - name: Commit files
          run: |
            version=$(cat version.txt)
            echo $version
            git add .
            git commit -m "Release version $version"
            git tag -a "$version" -m "$version"
            git push origin --tags
            git push

        
        # - name: Copy version file in VM
        #   run: |
        #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf /home/bianca/assignment1/version.txt"
        #     scp -rv /home/runner/work/assignment1/assignment1/version.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/bianca/assignment1/version.txt

        
