name: PR Validation
on: 
    push:
        branches: 
            - master
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and Run Docker Compose for Test
              run: |
                docker-compose -f docker-compose.yml up -d --build
                echo "build"
                # Validate Nginx configuration
                docker-compose -f docker-compose.yml exec -ti test nginx -t -c /etc/nginx/nginx.conf
                echo "nginx verif"
                # Validate PHP syntax
                docker-compose -f docker-compose.yml exec -ti test php -l /nginx_php/index.php
                echo "php verif"