name: Testing
on: 
  pull_request:
jobs:
    validate:
      environment: Test
      env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and Run Docker Compose 
            run: |
              docker-compose -f docker-compose.yml up -d --build
              # Validate Nginx configuration
              docker-compose -f docker-compose.yml exec -ti test nginx -t -c /etc/nginx/nginx.conf
              echo "nginx successful"
              # Validate PHP syntax
              docker-compose -f docker-compose.yml exec -ti test php -l /nginx_php/index.php
              echo "php successful"
    deployment:
      needs: validate
      environment: Test
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      runs-on: ubuntu-latest
      steps:
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.ID_RSA }}
            known_hosts: 'placeholder'

        - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

        - name: Checkout code
          uses: actions/checkout@v4


        - name: Copy Secrets into local file
          run: |
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> /home/runner/work/assignment1/assignment1/.env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> /home/runner/work/assignment1/assignment1/.env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> /home/runner/work/assignment1/assignment1/.env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> /home/runner/work/assignment1/assignment1/.env
            cat /home/runner/work/assignment1/assignment1/.env

        - name: Copy files with SCP
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf /home/bianca/assignment1"
            scp -rv /home/runner/work/assignment1/assignment1 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/bianca
            ls /home/runner/work/assignment1/assignment1
        - name: Make backup dir
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /home/bianca/backup"
        - name: Spin up containers
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd assignment1; docker compose down; docker compose up --build -d"
          
        - name: Make backup
          run: |
              timeout 60
              ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker exec mysql bash -c 'mysqldump -h db -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /backup/backup.sql'"
        - name: Copy backup files with SCP
          run: |
              scp -rv ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/bianca/backup /home/runner/work/assignment1/assignment1/backup
        - name: Upload database backup
          uses: actions/upload-artifact@v4
          with:
            name: Database Backup
            path: /home/runner/work/assignment1/assignment1/backup
            retention-days: 7