name: Testing
on: 
  pull_request:
jobs:
    validate:
      environment: Test
      env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and Run Docker compose for Test
            run: |
              docker-compose -f docker-compose.yml up -d --build
              # Validate Nginx configuration
              docker-compose -f docker-compose.yml exec -ti test nginx -t -c /etc/nginx/nginx.conf
              echo "nginx successful"
              # Validate PHP syntax
              docker-compose -f docker-compose.yml exec -ti test php -l /nginx_php/index.php
              echo "php successful"
    deployment:
      needs: validate
      environment: Test
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      runs-on: ubuntu-latest
      steps:
        - name: Verif 
          run: echo ${{ secrets.SSH_KEY }}
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_KEY }}
            known_hosts: 'placeholder'
        - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Copy secrets into local file
          run: |
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> /home/runner/work/firstAssignment/firstAssignment/.env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> /home/runner/work/firstAssignment/firstAssignment/.env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> /home/runner/work/firstAssignment/firstAssignment/.env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> /home/runner/work/firstAssignment/firstAssignment/.env
        - name: Copy files with SCP
          run: |
            scp -rv /home/runner/work/firstAssignment/firstAssignment ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home
            ls /home/runner/work/firstAssignment/firstAssignment/
        - name: Spin up containers
          run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd firstAssignment; docker compose down; docker compose up --build -d"