name: PR Validation
on: 
    push:
        branches: 
            - master
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and Run Docker Compose for Test
              run: |
                docker-compose -f docker-compose.yml up -d --build test
                docker-compose -f docker-compose.yml exec test nginx -t -c /etc/nginx/nginx.conf
                docker-compose -f docker-compose.yml exec test php -l /nginx_php/index.php