name: PR Validation
on: 
    pull_request:
        branches: 
            - testing
        
jobs:
    validate:
        environment: Test
        env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER: ${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            # - name: Verify secrets
            #   run: echo "$MYSQL_USER"
            # - name: Set environment variables
            #   run: |
            #       echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV
            #       echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $GITHUB_ENV
            #       echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_ENV
            
            #       echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
            - name: Build and Run Docker Compose for Test
              run: |
                docker-compose -f docker-compose.yml up -d --build
                echo "build"
                # Validate Nginx configuration
                docker-compose -f docker-compose.yml exec -ti test nginx -t -c /etc/nginx/nginx.conf
                echo "nginx verif"
                # Validate PHP syntax
                docker-compose -f docker-compose.yml exec -ti test php -l /nginx_php/index.php
                echo "php verif"